### ISSUE TITLE
Python 3.11対応

### ISSUE THREAD

**Issue by Xornet-Euphoria** [Xornet-Euphoria/pickaxe#1]
f-string内のダブルクォートは3.12から

```
$ python
Python 3.11.9 (main, Jul  3 2024, 11:24:12) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickaxe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xornet/repos/pickaxe/pickaxe/__init__.py", line 1, in <module>
    from .crafter import Crafter, AsciiCrafter, UnicodeCrafter
  File "/home/xornet/repos/pickaxe/pickaxe/crafter.py", line 17
    raise ValueError(f"{_b.to_bytes(1, "little")} is forbidden")
                                        ^^^^^^
SyntaxError: f-string: unmatched '('
>>>
```

**Comment by Xornet-Euphoria** [comment]
dfcbdf7a9bf7a93205f7066d11b2f359455d6b95 で対応
